### ISSUE TITLE
compiling symbol errors

### ISSUE THREAD

**Issue by deus-avertat** [Master-chan/BongoCatTablet#1]
getting errors compiling to do with the symbol [method getTopXX/method getBotXX etc..]
https://paste.ubuntu.com/p/jbJ4mG7WTg/
full compile log is there

**Comment by Master-chan** [comment]
If you're not using maven compiler you should install lombok for your IDE.
I you just want to build the project, I recommend you to install maven and do "mvn clean package" in project root.

**Comment by isaiaslpz** [comment]
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5:compile (default-compile) on project BongoCatTablet: Fatal error compiling: java.lang.ExceptionInInitializerError: com.sun.tools.javac.code.TypeTags -> [Help 1]
Using MVN 3.5.0

**Comment by Master-chan** [comment]
@isaiaslpz please create new issue and provide which JDK you're using for compilation.
